# Generated by Django 5.0.4 on 2024-06-26 16:58

from django.db import migrations


def set_rarity_level(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 < item.price < 20:
            item.rarity = 'Very Rare' 


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
    ]
