# Generated by Django 5.0.4 on 2024-06-26 16:58

from django.db import migrations


def set_rarity_level(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif item.price <= 20:
            item.rarity = 'Very Rare'
        elif item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'
        item.save()

def set_rarity_level_to_default(apps, schema_editor):
    items_model = apps.get_model('main_app', 'Item')

    for item in items_model.objects.all():
        item.rarity = items_model._meta.get_field('rarity').default
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity_level, set_rarity_level_to_default),
    ]
