# Generated by Django 5.0.6 on 2024-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_in_days', models.PositiveIntegerField()),
                ('estimated_hours', models.FloatField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
