# Generated by Django 5.0.6 on 2024-06-21 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration_in_days',
            field=models.PositiveIntegerField(verbose_name='Duration in Days'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.FloatField(verbose_name='Estimated Hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
