# Generated by Django 5.0.6 on 2024-07-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMage',
            fields=[
                ('mage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.mage')),
                ('time_magic_mastery', models.CharField(max_length=100)),
                ('temporal_shift_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('main_app.mage',),
        ),
        migrations.RenameField(
            model_name='demonhunter',
            old_name='temporal_shift_ability',
            new_name='demon_slaying_ability',
        ),
        migrations.RenameField(
            model_name='demonhunter',
            old_name='time_magic_mastery',
            new_name='weapon_type',
        ),
    ]
