# Generated by Django 5.0.6 on 2024-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_driver_drivinglicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
